package com.SIMRacingApps.SIMPlugins.iRacing;

import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;

import com.owlike.genson.Genson;

public class Yaml_parser {

    enum yaml_state {
        space,
        key,
        keysep,
        value,
        newline
    };

    public Yaml_parser() {
    }

    private void _storeData(Map<String,Object> m, StringBuilder key, StringBuilder value) {
        
        String s = value.toString().trim();

        try {
            if (s.startsWith("\"") && s.endsWith("\"")) {
                //"1234"
                //012345
                if (s.length() > 2)
                    m.put(key.toString(),s.substring(1, s.length() - 1));
                else
                    m.put(key.toString(),"");
            }
            else
            if (s.startsWith("0x")) {
                Integer i = Integer.parseInt(s.substring(2),16);
                m.put(key.toString(),i);
            }
            else {
                Integer i = Integer.parseInt(s);
                m.put(key.toString(),i);
            }
        }
        catch (NumberFormatException e) {
            try {
                Double d = Double.parseDouble(s);
                m.put(key.toString(),d);
            }
            catch (NumberFormatException e2) {
                m.put(key.toString(),s);
            }
        }
        
    }
    /*
    ---                    
    SessionInfo:
     Sessions:
     - SessionNum: 0
       SessionLaps: unlimited
       ResultsPositions:
       - Position: 1
         ClassPosition: 0
         CarIdx: 9
         Lap: 1
         Time: 46.022
         FastestLap: 1
         FastestTime: 46.022
         LastTime: 52.019
         LapsLed: 0
         LapsComplete: 3
         LapsDriven: 4.428
         Incidents: 0
         ReasonOutId: 0
         ReasonOutStr: Running
       SessionTime: 300.00 sec
       SessionNumLapsToAvg: 0
       SessionType: Practice
    ...
    */
    public TreeMap<String,Object> load(byte data[]) {
        TreeMap<String,Object> results= new TreeMap<String,Object>();
        ArrayList<Object> collections = new ArrayList<Object>();
        StringBuilder key             = new StringBuilder();
        StringBuilder value           = new StringBuilder();
        yaml_state state              = yaml_state.newline;  //start as a new line
        int prevDepth = -1;
        int depth = 0;

        collections.add(results);
        
        int len = data.length; //optimize this for speed
        for (int i=0; i < len; i++) {

            //convert byte to unsigned char
            char c = (char) ((int)data[i] & 0xFF);

            switch(c)
            {
            case ' ':
                if (state == yaml_state.key) {
                    key.append(c);          //add to existing key
                }
                else
                if (state == yaml_state.value) {        //add to existing value
                    value.append(c);
                }
                else
                if (state == yaml_state.newline || state == yaml_state.space) {
                    depth++;
                    state = yaml_state.space;
                }
                else
                if (state == yaml_state.keysep) {
                    state = yaml_state.value;
                }
                break;
            case '-':
                if (state == yaml_state.key) {
                    key.append(c);          //add to existing key
                }
                else
                if (state == yaml_state.value) {        //add to existing value
                    value.append(c);
                }
                else
                if (state == yaml_state.newline || state == yaml_state.space) {
                    
                    if (key.length() > 0) {  //do we have a key from the previous line
                        
                        //because the hyphen appears at the same depth as the key that defines it
                        //I'm going to increment it to make it unique because there's a space after it
                        depth++;
                        
                        //if this is a new depth level, create a new collection
                        if (depth > prevDepth) { 
                            //create a new map collection and add it to the previous
                            @SuppressWarnings("unchecked")
                            Map<String,Object>            m = (Map<String, Object>) collections.get(collections.size()-1);
                            ArrayList<Map<String,Object>> a = new ArrayList<Map<String,Object>>();
                            Map<String,Object>            n = new TreeMap<String,Object>();
                            
                            m.put(key.toString(), a);   //update previous map with the array
                            collections.add(a);         //track the collection
                            collections.add(n);         //track the collection
                            a.add(n);
                            
                            //TODO: If there's a value here, I don't think it's valid. Throw an error?
                            //      For now just ignore
                            //SessionInfo:
                            // Session: somevalue        <<<<<<<<
                            // - SessionNum: 1
                            //   SessionName: Qual
                            // - SessionNum: 2
                            //   SessionName: Race
                        }
                        else
                        //if this is an existing level, add the value to the collection
                        if (depth <= prevDepth) {
                            //SessionInfo:
                            // Session:
                            // - SessionNum: 1
                            //   SessionLaps: unlimited     <<<<<<<<
                            // - SessionNum: 2
                            //   SessionName: Race
                            @SuppressWarnings("unchecked")
                            Map<String,Object> m = (Map<String, Object>) collections.get(collections.size()-1);
                            _storeData(m,key,value);
                            
                            //if we're at the same level, add a new map to the array
                            if (depth == (prevDepth-1)) {
                                collections.remove(collections.size()-1);   //remove the current map
                                @SuppressWarnings("unchecked")
                                ArrayList<Map<String,Object>> a = (ArrayList<Map<String,Object>>)collections.get(collections.size()-1);
                                Map<String,Object>            n = new TreeMap<String,Object>();
                                a.add(n);           //add new map to array
                                collections.add(n); //add new map to the collections
                            }
                            else {
                                //collections at a higher depth, must be terminated
                                //SessionInfo:
                                // Session:
                                // - SessionNum: 1
                                //   SessionLaps: unlimited
                                // SessionExtra: somevalue      <<<<<<<<
                                while (depth < prevDepth) {
                                    if (collections.size() > 1)
                                        collections.remove(collections.size()-1);
                                    prevDepth--;
                                }
                                @SuppressWarnings("unchecked")
                                ArrayList<Map<String,Object>> a = (ArrayList<Map<String,Object>>)collections.get(collections.size()-1);
                                Map<String,Object>            n = new TreeMap<String,Object>();
                                a.add(n);           //add new map to array
                                collections.add(n); //add new map to the collections
                            }
                        }
                    }
                    
                    key   = new StringBuilder();  //start a new key
                    value = new StringBuilder();  //start a new value
                }
                break;
            case ':':
                if (state == yaml_state.key) {
                    //key is found, but hold that thought. Need to see what's next
                    state = yaml_state.keysep;
                }
                else
                if (state == yaml_state.value) {
                    value.append(c);
                }
                break;
            case '\n':
            case '\r':
                if(state != yaml_state.newline)
                {
                    state = yaml_state.newline;
                    prevDepth = depth;
                    depth = 0;
                }
                break;
            default:
                if (state == yaml_state.key) {
                    key.append(c);                //add to existing key
                }
                else
                if (state == yaml_state.value) {        //add to existing value
                    value.append(c);
                }
                else
                if (state == yaml_state.newline || state == yaml_state.space) {
                    
                    if (key.length() > 0) {  //do we have a key from the previous line
                        
                        //if this is a new depth level, create a new collection
                        if (depth > prevDepth) { 
                            //create a new map collection and add it to the previous
                            @SuppressWarnings("unchecked")
                            Map<String,Object> m = (Map<String, Object>) collections.get(collections.size()-1);
                            Map<String,Object> n = new TreeMap<String,Object>();
                            m.put(key.toString(), n);
                            collections.add(n);   //track the collection
                            
                            //TODO: If there's a value here, I don't think it's valid. Throw an error?
                            //      For now just ignore
                            //SessionInfo: somevalue        <<<<<<<<
                            // Session:
                            // - SessionNum: 1
                        }
                        else
                        //if this is an existing level, add the value to the collection
                        if (depth <= prevDepth) {
                            //SessionInfo:
                            // Session:
                            // - SessionNum: 1
                            //   SessionLaps: unlimited     <<<<<<<<
                            @SuppressWarnings("unchecked")
                            Map<String,Object> m = (Map<String, Object>) collections.get(collections.size()-1);
                            _storeData(m,key,value);

                            //collections at a higher depth, must be terminated
                            //SessionInfo:
                            // Session:
                            // - SessionNum: 1
                            //   SessionLaps: unlimited
                            // SessionExtra: somevalue      <<<<<<<<
                            while (depth < prevDepth) {
                                if (collections.size() > 1)
                                    collections.remove(collections.size()-1);
                                prevDepth--;
                            }
                        }
                    }
                    
                    key = new StringBuilder();          //start a new key
                    key.append(c);
                    value = new StringBuilder();        //start a new value
                    state = yaml_state.key;
                }
                break;
            }
        }
        return results;
    }

    //java -classpath SIMRacingAppsServer.exe com.SIMRacingApps.SIMPlugins.iRacing.Yaml
    public static void main(String[] args) {
        @SuppressWarnings("deprecation")
        Genson genson = new Genson.Builder().useIndentation(true).create();
        Yaml_parser y = new Yaml_parser();
        TreeMap<String,Object> m = y.load((
/*                  "---\n"
                + "SessionInfo:\n"
                + " Session:\n"
                + " - SessionNum: 1\n"
                + "   SessionName: Qual\n"
                + "   Results:\n"
                + "   - Position: 1\n"
                + "     CarIdx: 10\n"
                + "   - Position: 2\n"
                + "     CarIdx: 1\n"
                + " - SessionNum: 2\n"
                + "   SessionName: Race\n"
                + "CameraInfo:\n"
                + " Camera:\n"
                + "  CameraNum: 1\n"
                + "  CameraGroup: TV1\n"
                + " MoreCameraInfo: \"more\"\n"
                + " Hyphen: a-b\n"
                + " Colon: a:b\n"
                + " Space: a b\n"
                + "...\n"
*/
"---\n"
+"WeekendInfo:\n"
+" TrackName: phoenix oval\n"
+" TrackID: 104\n"
+" TrackLength: 1.62 km\n"
+" TrackDisplayName: Phoenix International Raceway\n"
+" TrackDisplayShortName: Phoenix\n"
+" TrackConfigName: Oval\n"
+" TrackCity: Phoenix\n"
+" TrackCountry: USA\n"
+" TrackAltitude: 291.67 m\n"
+" TrackLatitude: 33.375996 m\n"
+" TrackLongitude: -112.311381 m\n"
+" TrackNorthOffset: 4.3726 rad\n"
+" TrackNumTurns: 4\n"
+" TrackPitSpeedLimit: 72.00 kph\n"
+" TrackType: mile oval\n"
+" TrackDirection: left\n"
+" TrackWeatherType: Constant\n"
+" TrackSkies: Partly Cloudy\n"
+" TrackSurfaceTemp: 39.81 C\n"
+" TrackAirTemp: 25.56 C\n"
+" TrackAirPressure: 28.90 Hg\n"
+" TrackWindVel: 0.89 m/s\n"
+" TrackWindDir: 0.00 rad\n"
+" TrackRelativeHumidity: 55 %\n"
+" TrackFogLevel: 0 %\n"
+" TrackCleanup: 1\n"
+" TrackDynamicTrack: 1\n"
+" SeriesID: 259\n"
+" SeasonID: 1989\n"
+" SessionID: 90966816\n"
+" SubSessionID: 22181040\n"
+" LeagueID: 0\n"
+" Official: 1\n"
+" RaceWeek: 8\n"
+" EventType: Race\n"
+" Category: Oval\n"
+" SimMode: full\n"
+" TeamRacing: 0\n"
+" MinDrivers: 0\n"
+" MaxDrivers: 1\n"
+" DCRuleSet: None\n"
+" QualifierMustStartRace: 0\n"
+" NumCarClasses: 1\n"
+" NumCarTypes: 2\n"
+" HeatRacing: 0\n"
+" WeekendOptions:\n"
+"  NumStarters: 30\n"
+"  StartingGrid: 2x2 inline pole on left\n"
+"  QualifyScoring: best lap\n"
+"  CourseCautions: off\n"
+"  StandingStart: 0\n"
+"  Restarts: double file lapped cars behind\n"
+"  WeatherType: Constant\n"
+"  Skies: Partly Cloudy\n"
+"  WindDirection: N\n"
+"  WindSpeed: 3.22 km/h\n"
+"  WeatherTemp: 25.56 C\n"
+"  RelativeHumidity: 55 %\n"
+"  FogLevel: 0 %\n"
+"  TimeOfDay: 2:00 pm\n"
+"  Unofficial: 0\n"
+"  CommercialMode: consumer\n"
+"  NightMode: 0\n"
+"  IsFixedSetup: 0\n"
+"  StrictLapsChecking: default\n"
+"  HasOpenRegistration: 0\n"
+"  HardcoreLevel: 1\n"
+"  NumJokerLaps: 0\n"
+"  IncidentLimit: unlimited\n"
+" TelemetryOptions:\n"
+"  TelemetryDiskFile: \"\"\n"
+"\n"
+"SessionInfo:\n"
+" Sessions:\n"
+" - SessionNum: 0\n"
+"   SessionLaps: unlimited\n"
+"   SessionTime: 180.0000 sec\n"
+"   SessionNumLapsToAvg: 0\n"
+"   SessionType: Practice\n"
+"   SessionTrackRubberState: moderately high usage\n"
+"   SessionName: PRACTICE\n"
+"   SessionSubType: \n"
+"   SessionSkipped: 0\n"
+"   SessionRunGroupsUsed: 0\n"
+"   ResultsPositions:\n"
+"   - Position: 1\n"
+"     ClassPosition: 0\n"
+"     CarIdx: 5\n"
+"     Lap: 1\n"
+"     Time: 28.8936\n"
+"     FastestLap: 1\n"
+"     FastestTime: 28.8936\n"
+"     LastTime: 28.8936\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 1\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 2.609\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 2\n"
+"     ClassPosition: 1\n"
+"     CarIdx: 8\n"
+"     Lap: 1\n"
+"     Time: 29.2254\n"
+"     FastestLap: 1\n"
+"     FastestTime: 29.2254\n"
+"     LastTime: 29.3314\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 3.545\n"
+"     Incidents: 4\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 3\n"
+"     ClassPosition: 2\n"
+"     CarIdx: 17\n"
+"     Lap: 2\n"
+"     Time: 29.2861\n"
+"     FastestLap: 2\n"
+"     FastestTime: 29.2861\n"
+"     LastTime: 29.2861\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 3.522\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 4\n"
+"     ClassPosition: 3\n"
+"     CarIdx: 14\n"
+"     Lap: 1\n"
+"     Time: 29.3877\n"
+"     FastestLap: 1\n"
+"     FastestTime: 29.3877\n"
+"     LastTime: 29.3877\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 1\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 2.591\n"
+"     Incidents: 4\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 5\n"
+"     ClassPosition: 4\n"
+"     CarIdx: 6\n"
+"     Lap: 1\n"
+"     Time: 30.6505\n"
+"     FastestLap: 1\n"
+"     FastestTime: 30.6505\n"
+"     LastTime: 30.6505\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 1\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 2.447\n"
+"     Incidents: 1\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 6\n"
+"     ClassPosition: 5\n"
+"     CarIdx: 13\n"
+"     Lap: 1\n"
+"     Time: 30.9182\n"
+"     FastestLap: 1\n"
+"     FastestTime: 30.9182\n"
+"     LastTime: 30.9182\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 1\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 2.741\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 7\n"
+"     ClassPosition: 6\n"
+"     CarIdx: 12\n"
+"     Lap: 1\n"
+"     Time: 31.0344\n"
+"     FastestLap: 1\n"
+"     FastestTime: 31.0344\n"
+"     LastTime: 31.0344\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 1\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 2.877\n"
+"     Incidents: 2\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 8\n"
+"     ClassPosition: 7\n"
+"     CarIdx: 11\n"
+"     Lap: 1\n"
+"     Time: 45.2650\n"
+"     FastestLap: 1\n"
+"     FastestTime: 45.2650\n"
+"     LastTime: 45.2650\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 1\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 2.575\n"
+"     Incidents: 4\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 9\n"
+"     ClassPosition: 8\n"
+"     CarIdx: 10\n"
+"     Lap: 1\n"
+"     Time: 47.4883\n"
+"     FastestLap: 1\n"
+"     FastestTime: 47.4883\n"
+"     LastTime: 47.4883\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 1\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 1.976\n"
+"     Incidents: 4\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 10\n"
+"     ClassPosition: 9\n"
+"     CarIdx: 1\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 1.751\n"
+"     Incidents: 2\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 11\n"
+"     ClassPosition: 10\n"
+"     CarIdx: 2\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 12\n"
+"     ClassPosition: 11\n"
+"     CarIdx: 3\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 13\n"
+"     ClassPosition: 12\n"
+"     CarIdx: 4\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 14\n"
+"     ClassPosition: 13\n"
+"     CarIdx: 7\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.782\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 15\n"
+"     ClassPosition: 14\n"
+"     CarIdx: 9\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.947\n"
+"     Incidents: 4\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 16\n"
+"     ClassPosition: 15\n"
+"     CarIdx: 15\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 17\n"
+"     ClassPosition: 16\n"
+"     CarIdx: 16\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 18\n"
+"     ClassPosition: 17\n"
+"     CarIdx: 18\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   ResultsFastestLap:\n"
+"   - CarIdx: 5\n"
+"     FastestLap: 1\n"
+"     FastestTime: 28.8936\n"
+"   ResultsAverageLapTime: -1.0000\n"
+"   ResultsNumCautionFlags: 0\n"
+"   ResultsNumCautionLaps: 0\n"
+"   ResultsNumLeadChanges: 0\n"
+"   ResultsLapsComplete: -1\n"
+"   ResultsOfficial: 1\n"
+" - SessionNum: 1\n"
+"   SessionLaps: 2\n"
+"   SessionTime: 300.0000 sec\n"
+"   SessionNumLapsToAvg: 0\n"
+"   SessionType: Lone Qualify\n"
+"   SessionTrackRubberState: carry over\n"
+"   SessionName: QUALIFY\n"
+"   SessionSubType: \n"
+"   SessionSkipped: 0\n"
+"   SessionRunGroupsUsed: 0\n"
+"   ResultsPositions:\n"
+"   - Position: 1\n"
+"     ClassPosition: 0\n"
+"     CarIdx: 7\n"
+"     Lap: 1\n"
+"     Time: 28.8985\n"
+"     FastestLap: 1\n"
+"     FastestTime: 28.8985\n"
+"     LastTime: 29.2178\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 3.147\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 2\n"
+"     ClassPosition: 1\n"
+"     CarIdx: 5\n"
+"     Lap: 1\n"
+"     Time: 28.9235\n"
+"     FastestLap: 1\n"
+"     FastestTime: 28.9235\n"
+"     LastTime: 29.0319\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 3.106\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 3\n"
+"     ClassPosition: 2\n"
+"     CarIdx: 6\n"
+"     Lap: 1\n"
+"     Time: 29.0009\n"
+"     FastestLap: 1\n"
+"     FastestTime: 29.0009\n"
+"     LastTime: 29.4161\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 3.428\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 4\n"
+"     ClassPosition: 3\n"
+"     CarIdx: 16\n"
+"     Lap: 1\n"
+"     Time: 29.0991\n"
+"     FastestLap: 1\n"
+"     FastestTime: 29.0991\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 2.819\n"
+"     Incidents: 3\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 5\n"
+"     ClassPosition: 4\n"
+"     CarIdx: 9\n"
+"     Lap: 1\n"
+"     Time: 29.5590\n"
+"     FastestLap: 1\n"
+"     FastestTime: 29.5590\n"
+"     LastTime: 92.1412\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 2.970\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 6\n"
+"     ClassPosition: 5\n"
+"     CarIdx: 12\n"
+"     Lap: 1\n"
+"     Time: 29.5747\n"
+"     FastestLap: 1\n"
+"     FastestTime: 29.5747\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 2.801\n"
+"     Incidents: 2\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 7\n"
+"     ClassPosition: 6\n"
+"     CarIdx: 17\n"
+"     Lap: 2\n"
+"     Time: 29.5877\n"
+"     FastestLap: 2\n"
+"     FastestTime: 29.5877\n"
+"     LastTime: 29.5877\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 3.066\n"
+"     Incidents: 2\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 8\n"
+"     ClassPosition: 7\n"
+"     CarIdx: 13\n"
+"     Lap: 1\n"
+"     Time: 29.7492\n"
+"     FastestLap: 1\n"
+"     FastestTime: 29.7492\n"
+"     LastTime: 30.2538\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 4.857\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 9\n"
+"     ClassPosition: 8\n"
+"     CarIdx: 10\n"
+"     Lap: 2\n"
+"     Time: 31.6909\n"
+"     FastestLap: 2\n"
+"     FastestTime: 31.6909\n"
+"     LastTime: 31.6909\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 3.038\n"
+"     Incidents: 2\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 10\n"
+"     ClassPosition: 9\n"
+"     CarIdx: 1\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 4.787\n"
+"     Incidents: 2\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 11\n"
+"     ClassPosition: 10\n"
+"     CarIdx: 2\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 12\n"
+"     ClassPosition: 11\n"
+"     CarIdx: 3\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 13\n"
+"     ClassPosition: 12\n"
+"     CarIdx: 4\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 14\n"
+"     ClassPosition: 13\n"
+"     CarIdx: 11\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 2.890\n"
+"     Incidents: 6\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 15\n"
+"     ClassPosition: 14\n"
+"     CarIdx: 14\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 2.922\n"
+"     Incidents: 2\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 16\n"
+"     ClassPosition: 15\n"
+"     CarIdx: 8\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 17\n"
+"     ClassPosition: 16\n"
+"     CarIdx: 15\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 18\n"
+"     ClassPosition: 17\n"
+"     CarIdx: 18\n"
+"     Lap: 0\n"
+"     Time: -1.0000\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   ResultsFastestLap:\n"
+"   - CarIdx: 7\n"
+"     FastestLap: 1\n"
+"     FastestTime: 28.8985\n"
+"   ResultsAverageLapTime: -1.0000\n"
+"   ResultsNumCautionFlags: 0\n"
+"   ResultsNumCautionLaps: 0\n"
+"   ResultsNumLeadChanges: 0\n"
+"   ResultsLapsComplete: -1\n"
+"   ResultsOfficial: 1\n"
+" - SessionNum: 2\n"
+"   SessionLaps: 25\n"
+"   SessionTime: unlimited\n"
+"   SessionNumLapsToAvg: 0\n"
+"   SessionType: Race\n"
+"   SessionTrackRubberState: carry over\n"
+"   SessionName: RACE\n"
+"   SessionSubType: \n"
+"   SessionSkipped: 0\n"
+"   SessionRunGroupsUsed: 0\n"
+"   ResultsPositions:\n"
+"   - Position: 1\n"
+"     ClassPosition: 0\n"
+"     CarIdx: 5\n"
+"     Lap: 0\n"
+"     Time: 0.0000\n"
+"     FastestLap: 2\n"
+"     FastestTime: 28.9057\n"
+"     LastTime: 29.3744\n"
+"     LapsLed: 5\n"
+"     LapsComplete: 5\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 2\n"
+"     ClassPosition: 1\n"
+"     CarIdx: 7\n"
+"     Lap: 0\n"
+"     Time: 1.3474\n"
+"     FastestLap: 2\n"
+"     FastestTime: 29.1704\n"
+"     LastTime: 29.4634\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 5\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 3\n"
+"     ClassPosition: 2\n"
+"     CarIdx: 16\n"
+"     Lap: 0\n"
+"     Time: 2.1993\n"
+"     FastestLap: 4\n"
+"     FastestTime: 29.2438\n"
+"     LastTime: 29.2438\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 4\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 4\n"
+"     ClassPosition: 3\n"
+"     CarIdx: 6\n"
+"     Lap: 0\n"
+"     Time: 3.1020\n"
+"     FastestLap: 4\n"
+"     FastestTime: 29.3347\n"
+"     LastTime: 29.3347\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 4\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 5\n"
+"     ClassPosition: 4\n"
+"     CarIdx: 1\n"
+"     Lap: 0\n"
+"     Time: 3.2885\n"
+"     FastestLap: 4\n"
+"     FastestTime: 29.0175\n"
+"     LastTime: 29.0175\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 4\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 6\n"
+"     ClassPosition: 5\n"
+"     CarIdx: 12\n"
+"     Lap: 0\n"
+"     Time: 4.7418\n"
+"     FastestLap: 4\n"
+"     FastestTime: 29.7926\n"
+"     LastTime: 29.7926\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 4\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 7\n"
+"     ClassPosition: 6\n"
+"     CarIdx: 10\n"
+"     Lap: 0\n"
+"     Time: 4.7833\n"
+"     FastestLap: 4\n"
+"     FastestTime: 29.6649\n"
+"     LastTime: 29.6649\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 4\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 8\n"
+"     ClassPosition: 7\n"
+"     CarIdx: 17\n"
+"     Lap: 0\n"
+"     Time: 5.0720\n"
+"     FastestLap: 2\n"
+"     FastestTime: 29.5014\n"
+"     LastTime: 29.8245\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 4\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 9\n"
+"     ClassPosition: 8\n"
+"     CarIdx: 4\n"
+"     Lap: 0\n"
+"     Time: 5.5616\n"
+"     FastestLap: 3\n"
+"     FastestTime: 29.4859\n"
+"     LastTime: 29.7429\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 4\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 10\n"
+"     ClassPosition: 9\n"
+"     CarIdx: 9\n"
+"     Lap: 0\n"
+"     Time: 5.5635\n"
+"     FastestLap: 3\n"
+"     FastestTime: 29.7588\n"
+"     LastTime: 29.9091\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 4\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 11\n"
+"     ClassPosition: 10\n"
+"     CarIdx: 18\n"
+"     Lap: 0\n"
+"     Time: 14.2958\n"
+"     FastestLap: 3\n"
+"     FastestTime: 30.0028\n"
+"     LastTime: 30.1206\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 4\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 12\n"
+"     ClassPosition: 11\n"
+"     CarIdx: 13\n"
+"     Lap: 2\n"
+"     Time: 59.5218\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 3\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 13\n"
+"     ClassPosition: 12\n"
+"     CarIdx: 3\n"
+"     Lap: 2\n"
+"     Time: 66.9035\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 2\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 14\n"
+"     ClassPosition: 13\n"
+"     CarIdx: 14\n"
+"     Lap: 3\n"
+"     Time: 53.5051\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 1\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 15\n"
+"     ClassPosition: 14\n"
+"     CarIdx: 11\n"
+"     Lap: 3\n"
+"     Time: 82.7592\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 1\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   - Position: 16\n"
+"     ClassPosition: 15\n"
+"     CarIdx: 8\n"
+"     Lap: 4\n"
+"     Time: 0.0140\n"
+"     FastestLap: -1\n"
+"     FastestTime: -1.0000\n"
+"     LastTime: -1.0000\n"
+"     LapsLed: 0\n"
+"     LapsComplete: 0\n"
+"     JokerLapsComplete: 0\n"
+"     LapsDriven: 0.000\n"
+"     Incidents: 0\n"
+"     ReasonOutId: 0\n"
+"     ReasonOutStr: Running\n"
+"   ResultsFastestLap:\n"
+"   - CarIdx: 5\n"
+"     FastestLap: 2\n"
+"     FastestTime: 28.9057\n"
+"   ResultsAverageLapTime: 29.9844\n"
+"   ResultsNumCautionFlags: 0\n"
+"   ResultsNumCautionLaps: 0\n"
+"   ResultsNumLeadChanges: 0\n"
+"   ResultsLapsComplete: 5\n"
+"   ResultsOfficial: 0\n"
+"\n"
+"QualifyResultsInfo:\n"
+" Results:\n"
+" - Position: 0\n"
+"   ClassPosition: 0\n"
+"   CarIdx: 7\n"
+"   FastestLap: 1\n"
+"   FastestTime: 28.8985\n"
+" - Position: 1\n"
+"   ClassPosition: 1\n"
+"   CarIdx: 5\n"
+"   FastestLap: 1\n"
+"   FastestTime: 28.9235\n"
+" - Position: 2\n"
+"   ClassPosition: 2\n"
+"   CarIdx: 6\n"
+"   FastestLap: 1\n"
+"   FastestTime: 29.0009\n"
+" - Position: 3\n"
+"   ClassPosition: 3\n"
+"   CarIdx: 16\n"
+"   FastestLap: 1\n"
+"   FastestTime: 29.0991\n"
+" - Position: 4\n"
+"   ClassPosition: 4\n"
+"   CarIdx: 9\n"
+"   FastestLap: 1\n"
+"   FastestTime: 29.5590\n"
+" - Position: 5\n"
+"   ClassPosition: 5\n"
+"   CarIdx: 12\n"
+"   FastestLap: 1\n"
+"   FastestTime: 29.5747\n"
+" - Position: 6\n"
+"   ClassPosition: 6\n"
+"   CarIdx: 17\n"
+"   FastestLap: 2\n"
+"   FastestTime: 29.5877\n"
+" - Position: 7\n"
+"   ClassPosition: 7\n"
+"   CarIdx: 13\n"
+"   FastestLap: 1\n"
+"   FastestTime: 29.7492\n"
+" - Position: 8\n"
+"   ClassPosition: 8\n"
+"   CarIdx: 10\n"
+"   FastestLap: 2\n"
+"   FastestTime: 31.6909\n"
+" - Position: 9\n"
+"   ClassPosition: 9\n"
+"   CarIdx: 1\n"
+"   FastestLap: 0\n"
+"   FastestTime: -1.0000\n"
+" - Position: 10\n"
+"   ClassPosition: 10\n"
+"   CarIdx: 3\n"
+"   FastestLap: 0\n"
+"   FastestTime: -1.0000\n"
+" - Position: 11\n"
+"   ClassPosition: 11\n"
+"   CarIdx: 4\n"
+"   FastestLap: 0\n"
+"   FastestTime: -1.0000\n"
+" - Position: 12\n"
+"   ClassPosition: 12\n"
+"   CarIdx: 11\n"
+"   FastestLap: 0\n"
+"   FastestTime: -1.0000\n"
+" - Position: 13\n"
+"   ClassPosition: 13\n"
+"   CarIdx: 14\n"
+"   FastestLap: 0\n"
+"   FastestTime: -1.0000\n"
+" - Position: 14\n"
+"   ClassPosition: 14\n"
+"   CarIdx: 8\n"
+"   FastestLap: 0\n"
+"   FastestTime: -1.0000\n"
+" - Position: 15\n"
+"   ClassPosition: 15\n"
+"   CarIdx: 18\n"
+"   FastestLap: 0\n"
+"   FastestTime: -1.0000\n"
+" - Position: 16\n"
+"   ClassPosition: 16\n"
+"   CarIdx: 2\n"
+"   FastestLap: 0\n"
+"   FastestTime: -1.0000\n"
+" - Position: 17\n"
+"   ClassPosition: 17\n"
+"   CarIdx: 15\n"
+"   FastestLap: 0\n"
+"   FastestTime: -1.0000\n"
+"\n"
+"CameraInfo:\n"
+" Groups:\n"
+" - GroupNum: 1\n"
+"   GroupName: Nose\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamNose\n"
+" - GroupNum: 2\n"
+"   GroupName: Gearbox\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamGearbox\n"
+" - GroupNum: 3\n"
+"   GroupName: Roll Bar\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamRoll Bar\n"
+" - GroupNum: 4\n"
+"   GroupName: LF Susp\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamLF Susp\n"
+" - GroupNum: 5\n"
+"   GroupName: LR Susp\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamLR Susp\n"
+" - GroupNum: 6\n"
+"   GroupName: Gyro\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamGyro\n"
+" - GroupNum: 7\n"
+"   GroupName: RF Susp\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamRF Susp\n"
+" - GroupNum: 8\n"
+"   GroupName: RR Susp\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamRR Susp\n"
+" - GroupNum: 9\n"
+"   GroupName: Cockpit\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamCockpit\n"
+" - GroupNum: 10\n"
+"   GroupName: Scenic\n"
+"   IsScenic: true\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: Scenic_00\n"
+"   - CameraNum: 2\n"
+"     CameraName: Scenic_02\n"
+"   - CameraNum: 3\n"
+"     CameraName: Scenic_03\n"
+"   - CameraNum: 4\n"
+"     CameraName: Scenic_04\n"
+"   - CameraNum: 5\n"
+"     CameraName: Scenic_05\n"
+"   - CameraNum: 6\n"
+"     CameraName: Scenic_01\n"
+" - GroupNum: 11\n"
+"   GroupName: TV1\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamTV1_00\n"
+"   - CameraNum: 2\n"
+"     CameraName: CamTV1_01\n"
+"   - CameraNum: 3\n"
+"     CameraName: CamTV1_02\n"
+"   - CameraNum: 4\n"
+"     CameraName: CamTV1_03\n"
+" - GroupNum: 12\n"
+"   GroupName: TV2\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamTV2_00\n"
+"   - CameraNum: 2\n"
+"     CameraName: CamTV2_01\n"
+"   - CameraNum: 3\n"
+"     CameraName: CamTV2_02\n"
+"   - CameraNum: 4\n"
+"     CameraName: CamTV2_03\n"
+"   - CameraNum: 5\n"
+"     CameraName: CamTV2_04\n"
+" - GroupNum: 13\n"
+"   GroupName: TV3\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamTV3_00\n"
+"   - CameraNum: 2\n"
+"     CameraName: CamTV3_01\n"
+" - GroupNum: 14\n"
+"   GroupName: Pit Lane\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamPit Lane\n"
+" - GroupNum: 15\n"
+"   GroupName: Pit Lane 2\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamPit Lane 2\n"
+" - GroupNum: 16\n"
+"   GroupName: Chopper\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamChopper\n"
+" - GroupNum: 17\n"
+"   GroupName: Blimp\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamBlimp\n"
+" - GroupNum: 18\n"
+"   GroupName: Chase\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamChase\n"
+" - GroupNum: 19\n"
+"   GroupName: Far Chase\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamFar Chase\n"
+" - GroupNum: 20\n"
+"   GroupName: Rear Chase\n"
+"   Cameras:\n"
+"   - CameraNum: 1\n"
+"     CameraName: CamRear Chase\n"
+"\n"
+"RadioInfo:\n"
+" SelectedRadioNum: 0\n"
+" Radios:\n"
+" - RadioNum: 0\n"
+"   HopCount: 2\n"
+"   NumFrequencies: 6\n"
+"   TunedToFrequencyNum: 0\n"
+"   ScanningIsOn: 1\n"
+"   Frequencies:\n"
+"   - FrequencyNum: 0\n"
+"     FrequencyName: \"@SPECTATORS\"\n"
+"     Priority: 0\n"
+"     CarIdx: -1\n"
+"     EntryIdx: -1\n"
+"     ClubID: 0\n"
+"     CanScan: 1\n"
+"     CanSquawk: 1\n"
+"     Muted: 0\n"
+"     IsMutable: 1\n"
+"     IsDeletable: 0\n"
+"   - FrequencyNum: 1\n"
+"     FrequencyName: \"@DRIVERS\"\n"
+"     Priority: 15\n"
+"     CarIdx: -1\n"
+"     EntryIdx: -1\n"
+"     ClubID: 0\n"
+"     CanScan: 1\n"
+"     CanSquawk: 0\n"
+"     Muted: 0\n"
+"     IsMutable: 1\n"
+"     IsDeletable: 0\n"
+"   - FrequencyNum: 2\n"
+"     FrequencyName: \"@ALLTEAMS\"\n"
+"     Priority: 12\n"
+"     CarIdx: -1\n"
+"     EntryIdx: -1\n"
+"     ClubID: 0\n"
+"     CanScan: 1\n"
+"     CanSquawk: 0\n"
+"     Muted: 0\n"
+"     IsMutable: 1\n"
+"     IsDeletable: 0\n"
+"   - FrequencyNum: 3\n"
+"     FrequencyName: \"@RACECONTROL\"\n"
+"     Priority: 80\n"
+"     CarIdx: -1\n"
+"     EntryIdx: -1\n"
+"     ClubID: 0\n"
+"     CanScan: 1\n"
+"     CanSquawk: 0\n"
+"     Muted: 0\n"
+"     IsMutable: 0\n"
+"     IsDeletable: 0\n"
+"   - FrequencyNum: 4\n"
+"     FrequencyName: \"@PRIVATE\"\n"
+"     Priority: 70\n"
+"     CarIdx: -1\n"
+"     EntryIdx: 19\n"
+"     ClubID: 0\n"
+"     CanScan: 1\n"
+"     CanSquawk: 1\n"
+"     Muted: 0\n"
+"     IsMutable: 0\n"
+"     IsDeletable: 0\n"
+"   - FrequencyNum: 5\n"
+"     FrequencyName: \"@IROC\"\n"
+"     Priority: 50\n"
+"     CarIdx: -1\n"
+"     EntryIdx: -1\n"
+"     ClubID: 0\n"
+"     CanScan: 1\n"
+"     CanSquawk: 1\n"
+"     Muted: 0\n"
+"     IsMutable: 1\n"
+"     IsDeletable: 1\n"
+"\n"
+"DriverInfo:\n"
+" DriverCarIdx: 63\n"
+" DriverUserID: 44175\n"
+" PaceCarIdx: 0\n"
+" DriverHeadPosX: -0.085\n"
+" DriverHeadPosY: 0.466\n"
+" DriverHeadPosZ: 0.620\n"
+" DriverCarIdleRPM: 1200.000\n"
+" DriverCarRedLine: 9000.000\n"
+" DriverCarFuelKgPerLtr: 0.750\n"
+" DriverCarFuelMaxLtr: 70.753\n"
+" DriverCarMaxFuelPct: 1.000\n"
+" DriverCarSLFirstRPM: 7600.000\n"
+" DriverCarSLShiftRPM: 8600.000\n"
+" DriverCarSLLastRPM: 8600.000\n"
+" DriverCarSLBlinkRPM: 9000.000\n"
+" DriverPitTrkPct: 0.207580\n"
+" DriverCarEstLapTime: 28.3179\n"
+" DriverSetupName: phoenix_oval.sto\n"
+" DriverSetupIsModified: 0\n"
+" DriverSetupLoadTypeName: user\n"
+" DriverSetupPassedTech: 1\n"
+" DriverIncidentCount: 0\n"
+" Drivers:\n"
+" - CarIdx: 0\n"
+"   UserName: Pace Car\n"
+"   AbbrevName: Car, P\n"
+"   Initials: PC\n"
+"   UserID: -1\n"
+"   TeamID: 0\n"
+"   TeamName: Pace Car\n"
+"   CarNumber: \"0\"\n"
+"   CarNumberRaw: 0\n"
+"   CarPath: safety pcfr500s\n"
+"   CarClassID: 11\n"
+"   CarID: 32\n"
+"   CarIsPaceCar: 1\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: safety pcfr500s\n"
+"   CarScreenNameShort: safety pcfr500s\n"
+"   CarClassShortName: \n"
+"   CarClassRelSpeed: 0\n"
+"   CarClassLicenseLevel: 0\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 0\n"
+"   LicLevel: 1\n"
+"   LicSubLevel: 0\n"
+"   LicString: R 0.00\n"
+"   LicColor: 0xffffff\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 0,ffffff,ffffff,ffffff\n"
+"   HelmetDesignStr: 0,ffffff,ffffff,ffffff\n"
+"   SuitDesignStr: 0,ffffff,ffffff,ffffff\n"
+"   CarNumberDesignStr: 0,0,ffffff,ffffff,ffffff\n"
+"   CarSponsor_1: 0\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: -none-\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 1\n"
+"   UserName: Wyatt Foster\n"
+"   AbbrevName: Foster, W\n"
+"   Initials: WF\n"
+"   UserID: 60672\n"
+"   TeamID: 0\n"
+"   TeamName: Wyatt Foster\n"
+"   CarNumber: \"54\"\n"
+"   CarNumberRaw: 54\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 2428\n"
+"   LicLevel: 18\n"
+"   LicSubLevel: 214\n"
+"   LicString: A 2.14\n"
+"   LicColor: 0x0153db\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 13,031adc,f9e9e9,000000\n"
+"   HelmetDesignStr: 40,ffffff,000000,0921f5\n"
+"   SuitDesignStr: 4,ffffff,2a3ef7,000000\n"
+"   CarNumberDesignStr: 0,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 1\n"
+"   CarSponsor_2: 1\n"
+"   ClubName: Carolina\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 2\n"
+"   UserName: Jonathan Morrison3\n"
+"   AbbrevName: Morrison3, J\n"
+"   Initials: JM\n"
+"   UserID: 251772\n"
+"   TeamID: 0\n"
+"   TeamName: Jonathan Morrison3\n"
+"   CarNumber: \"1\"\n"
+"   CarNumberRaw: 1\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 2213\n"
+"   LicLevel: 18\n"
+"   LicSubLevel: 295\n"
+"   LicString: A 2.95\n"
+"   LicColor: 0x0153db\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 24,cc2314,41ec18,0d0f01\n"
+"   HelmetDesignStr: 10,15ec13,e8e711,1e1a1a\n"
+"   SuitDesignStr: 27,191515,0e110e,ed2129\n"
+"   CarNumberDesignStr: 2,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 0\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: New England\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 3\n"
+"   UserName: David White2\n"
+"   AbbrevName: White2, D\n"
+"   Initials: DW\n"
+"   UserID: 52791\n"
+"   TeamID: 0\n"
+"   TeamName: David White2\n"
+"   CarNumber: \"2\"\n"
+"   CarNumberRaw: 2\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 2134\n"
+"   LicLevel: 14\n"
+"   LicSubLevel: 235\n"
+"   LicString: B 2.35\n"
+"   LicColor: 0x00c702\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 0,000000,cccccc,666666\n"
+"   HelmetDesignStr: 68,26ddeb,ffffff,000000\n"
+"   SuitDesignStr: 0,26ddeb,26ddeb,000000\n"
+"   CarNumberDesignStr: 0,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 0\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: Atlantic\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 4\n"
+"   UserName: Jan W. Roestenskar\n"
+"   AbbrevName: Roestenskar, J\n"
+"   Initials: JR\n"
+"   UserID: 104400\n"
+"   TeamID: 0\n"
+"   TeamName: Jan W. Roestenskar\n"
+"   CarNumber: \"44\"\n"
+"   CarNumberRaw: 44\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1973\n"
+"   LicLevel: 19\n"
+"   LicSubLevel: 341\n"
+"   LicString: A 3.41\n"
+"   LicColor: 0x0153db\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 32,eb0a13,fe9f06,f5f529\n"
+"   HelmetDesignStr: 54,000000,fc0706,feec04\n"
+"   SuitDesignStr: 14,fc0706,feec04,000000\n"
+"   CarNumberDesignStr: 0,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 0\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: Scandinavia\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 5\n"
+"   UserName: Zach Harris\n"
+"   AbbrevName: Harris, Z\n"
+"   Initials: ZH\n"
+"   UserID: 302208\n"
+"   TeamID: 0\n"
+"   TeamName: Zach Harris\n"
+"   CarNumber: \"054\"\n"
+"   CarNumberRaw: 3054\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1847\n"
+"   LicLevel: 11\n"
+"   LicSubLevel: 334\n"
+"   LicString: C 3.34\n"
+"   LicColor: 0xfeec04\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 24,081db4,ffffff,000000;ffffff\n"
+"   HelmetDesignStr: 28,000000,000000,2a3795\n"
+"   SuitDesignStr: 1,ffffff,111111,5481fc\n"
+"   CarNumberDesignStr: 3,0,ffffff,2a3795,000000\n"
+"   CarSponsor_1: 151\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: Florida\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 6\n"
+"   UserName: Jason Yates3\n"
+"   AbbrevName: Yates3, J\n"
+"   Initials: JY\n"
+"   UserID: 312187\n"
+"   TeamID: 0\n"
+"   TeamName: Jason Yates3\n"
+"   CarNumber: \"3\"\n"
+"   CarNumberRaw: 3\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1347\n"
+"   LicLevel: 6\n"
+"   LicSubLevel: 271\n"
+"   LicString: D 2.71\n"
+"   LicColor: 0xfc8a27\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 1,111111,ffffff,5481fc\n"
+"   HelmetDesignStr: 5,111111,bb0b07,000000\n"
+"   SuitDesignStr: 9,111111,bb0b07,111111\n"
+"   CarNumberDesignStr: 0,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 0\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: Virginias\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 7\n"
+"   UserName: Harold Griffith\n"
+"   AbbrevName: Griffith, H\n"
+"   Initials: HG\n"
+"   UserID: 281644\n"
+"   TeamID: 0\n"
+"   TeamName: Harold Griffith\n"
+"   CarNumber: \"044\"\n"
+"   CarNumberRaw: 3044\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1310\n"
+"   LicLevel: 19\n"
+"   LicSubLevel: 371\n"
+"   LicString: A 3.71\n"
+"   LicColor: 0x0153db\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 12,fcc0f1,f8f70d,e7ea0b;081bd4\n"
+"   HelmetDesignStr: 17,0917e1,f7eb08,030330\n"
+"   SuitDesignStr: 30,0818e7,ece927,1c2bf2\n"
+"   CarNumberDesignStr: 1,0,0b0ef4,0e1cb9,edea21\n"
+"   CarSponsor_1: 1\n"
+"   CarSponsor_2: 89\n"
+"   ClubName: Ohio\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 8\n"
+"   UserName: James Ledford\n"
+"   AbbrevName: Ledford, J\n"
+"   Initials: JL\n"
+"   UserID: 302345\n"
+"   TeamID: 0\n"
+"   TeamName: James Ledford\n"
+"   CarNumber: \"25\"\n"
+"   CarNumberRaw: 25\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1280\n"
+"   LicLevel: 6\n"
+"   LicSubLevel: 250\n"
+"   LicString: D 2.50\n"
+"   LicColor: 0xfc8a27\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 9,0c0d0c,eb0a14,f7ed18\n"
+"   HelmetDesignStr: 1,000000,000000,000000\n"
+"   SuitDesignStr: 1,ffffff,1f2892,7de54c\n"
+"   CarNumberDesignStr: 43,0,f8f7f7,030202,000000\n"
+"   CarSponsor_1: 72\n"
+"   CarSponsor_2: 8\n"
+"   ClubName: Atlantic\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 9\n"
+"   UserName: Graeme Slack\n"
+"   AbbrevName: Slack, G\n"
+"   Initials: GS\n"
+"   UserID: 305279\n"
+"   TeamID: 0\n"
+"   TeamName: Graeme Slack\n"
+"   CarNumber: \"222\"\n"
+"   CarNumberRaw: 222\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1262\n"
+"   LicLevel: 6\n"
+"   LicSubLevel: 285\n"
+"   LicString: D 2.85\n"
+"   LicColor: 0xfc8a27\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 28,04060b,fdf7f7,1231c4,edeffc\n"
+"   HelmetDesignStr: 40,284a94,000000,fce3e3\n"
+"   SuitDesignStr: 27,284a94,ffffff,111111\n"
+"   CarNumberDesignStr: 7,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 1\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: UK and I\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 10\n"
+"   UserName: Harley Hicks\n"
+"   AbbrevName: Hicks, H\n"
+"   Initials: HH\n"
+"   UserID: 311635\n"
+"   TeamID: 0\n"
+"   TeamName: Harley Hicks\n"
+"   CarNumber: \"69\"\n"
+"   CarNumberRaw: 69\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1350\n"
+"   LicLevel: 2\n"
+"   LicSubLevel: 250\n"
+"   LicString: R 2.50\n"
+"   LicColor: 0xfc0706\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 9,5c0896,ee2111,ffffff\n"
+"   HelmetDesignStr: 1,5481fc,111111,ffffff\n"
+"   SuitDesignStr: 1,5481fc,111111,ffffff\n"
+"   CarNumberDesignStr: 18,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 8\n"
+"   CarSponsor_2: 51\n"
+"   ClubName: Florida\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 11\n"
+"   UserName: William Priddy\n"
+"   AbbrevName: Priddy, W\n"
+"   Initials: WP\n"
+"   UserID: 312740\n"
+"   TeamID: 0\n"
+"   TeamName: William Priddy\n"
+"   CarNumber: \"4\"\n"
+"   CarNumberRaw: 4\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1350\n"
+"   LicLevel: 2\n"
+"   LicSubLevel: 250\n"
+"   LicString: R 2.50\n"
+"   LicColor: 0xfc0706\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 1,111111,ffee47,0300c2\n"
+"   HelmetDesignStr: 1,111111,ffee47,0300c2\n"
+"   SuitDesignStr: 1,111111,ffee47,0300c2\n"
+"   CarNumberDesignStr: 0,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 0\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: Carolina\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 12\n"
+"   UserName: Trevor Craun\n"
+"   AbbrevName: Craun, T\n"
+"   Initials: TC\n"
+"   UserID: 312676\n"
+"   TeamID: 0\n"
+"   TeamName: Trevor Craun\n"
+"   CarNumber: \"5\"\n"
+"   CarNumberRaw: 5\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1345\n"
+"   LicLevel: 2\n"
+"   LicSubLevel: 267\n"
+"   LicString: R 2.67\n"
+"   LicColor: 0xfc0706\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 1,111111,b82f37,284a94\n"
+"   HelmetDesignStr: 1,111111,b82f37,284a94\n"
+"   SuitDesignStr: 1,111111,b82f37,284a94\n"
+"   CarNumberDesignStr: 0,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 0\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: Virginias\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 13\n"
+"   UserName: George Smart\n"
+"   AbbrevName: Smart, G\n"
+"   Initials: GS\n"
+"   UserID: 312777\n"
+"   TeamID: 0\n"
+"   TeamName: George Smart\n"
+"   CarNumber: \"6\"\n"
+"   CarNumberRaw: 6\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1345\n"
+"   LicLevel: 2\n"
+"   LicSubLevel: 253\n"
+"   LicString: R 2.53\n"
+"   LicColor: 0xfc0706\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 1,111111,0300c2,ffee47\n"
+"   HelmetDesignStr: 1,111111,0300c2,ffee47\n"
+"   SuitDesignStr: 1,111111,0300c2,ffee47\n"
+"   CarNumberDesignStr: 0,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 0\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: UK and I\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 14\n"
+"   UserName: Stephen Hynds\n"
+"   AbbrevName: Hynds, S\n"
+"   Initials: SH\n"
+"   UserID: 217842\n"
+"   TeamID: 0\n"
+"   TeamName: Stephen Hynds\n"
+"   CarNumber: \"8\"\n"
+"   CarNumberRaw: 8\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1319\n"
+"   LicLevel: 2\n"
+"   LicSubLevel: 254\n"
+"   LicString: R 2.54\n"
+"   LicColor: 0xfc0706\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 5,135324,111111,5e5e5e\n"
+"   HelmetDesignStr: 2,135324,111111,5e5e5e\n"
+"   SuitDesignStr: 2,135324,111111,5e5e5e\n"
+"   CarNumberDesignStr: 0,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 2\n"
+"   CarSponsor_2: 97\n"
+"   ClubName: UK and I\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 15\n"
+"   UserName: Mario Rini\n"
+"   AbbrevName: Rini, M\n"
+"   Initials: MR\n"
+"   UserID: 178129\n"
+"   TeamID: 0\n"
+"   TeamName: Mario Rini\n"
+"   CarNumber: \"61\"\n"
+"   CarNumberRaw: 61\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1156\n"
+"   LicLevel: 20\n"
+"   LicSubLevel: 417\n"
+"   LicString: A 4.17\n"
+"   LicColor: 0x0153db\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 0,0a0a0b,0a0a0b,0a0a0b,0b0a0a\n"
+"   HelmetDesignStr: 17,09090b,f6f3f3,080807\n"
+"   SuitDesignStr: 28,b2b0a4,084796,fafafa\n"
+"   CarNumberDesignStr: 0,3,fafafa,f60e0e,1385f6\n"
+"   CarSponsor_1: 0\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: Michigan\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 16\n"
+"   UserName: Brien Walters\n"
+"   AbbrevName: Walters, B\n"
+"   Initials: BW\n"
+"   UserID: 301710\n"
+"   TeamID: 0\n"
+"   TeamName: Brien Walters\n"
+"   CarNumber: \"05\"\n"
+"   CarNumberRaw: 2005\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1139\n"
+"   LicLevel: 6\n"
+"   LicSubLevel: 235\n"
+"   LicString: D 2.35\n"
+"   LicColor: 0xfc8a27\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 12,0746f2,ee1124,f3f2f2;f5f4f5\n"
+"   HelmetDesignStr: 17,263aed,5481fc,111111\n"
+"   SuitDesignStr: 1,ffffff,5481fc,111111\n"
+"   CarNumberDesignStr: 54,0,f7ee18,030202,d9d108\n"
+"   CarSponsor_1: 1\n"
+"   CarSponsor_2: 9\n"
+"   ClubName: Texas\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 17\n"
+"   UserName: Trevor Erhardt\n"
+"   AbbrevName: Erhardt, T\n"
+"   Initials: TE\n"
+"   UserID: 312291\n"
+"   TeamID: 0\n"
+"   TeamName: Trevor Erhardt\n"
+"   CarNumber: \"7\"\n"
+"   CarNumberRaw: 7\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1289\n"
+"   LicLevel: 2\n"
+"   LicSubLevel: 241\n"
+"   LicString: R 2.41\n"
+"   LicColor: 0xfc0706\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 5,000000,e69533,ffffff\n"
+"   HelmetDesignStr: 1,135324,111111,5e5e5e\n"
+"   SuitDesignStr: 1,135324,111111,5e5e5e\n"
+"   CarNumberDesignStr: 0,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 44\n"
+"   CarSponsor_2: 73\n"
+"   ClubName: Plains\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 18\n"
+"   UserName: Neal Ives\n"
+"   AbbrevName: Ives, N\n"
+"   Initials: NI\n"
+"   UserID: 281641\n"
+"   TeamID: 0\n"
+"   TeamName: Neal Ives\n"
+"   CarNumber: \"52\"\n"
+"   CarNumberRaw: 52\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 1124\n"
+"   LicLevel: 18\n"
+"   LicSubLevel: 239\n"
+"   LicString: A 2.39\n"
+"   LicColor: 0x0153db\n"
+"   IsSpectator: 0\n"
+"   CarDesignStr: 27,000000,ffb30a,4efd55\n"
+"   HelmetDesignStr: 63,000000,06f93a,ffffff\n"
+"   SuitDesignStr: 22,030203,18f757,f9b734\n"
+"   CarNumberDesignStr: 0,0,ffffff,777777,000000\n"
+"   CarSponsor_1: 0\n"
+"   CarSponsor_2: 0\n"
+"   ClubName: UK and I\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: -1\n"
+"   TeamIncidentCount: -1\n"
+" - CarIdx: 63\n"
+"   UserName: Jeffrey Gilliam\n"
+"   AbbrevName: \n"
+"   Initials: \n"
+"   UserID: 44175\n"
+"   TeamID: 0\n"
+"   TeamName: Jeffrey Gilliam\n"
+"   CarNumber: \"61\"\n"
+"   CarNumberRaw: 61\n"
+"   CarPath: trucks silverado\n"
+"   CarClassID: 17\n"
+"   CarID: 20\n"
+"   CarIsPaceCar: 0\n"
+"   CarIsAI: 0\n"
+"   CarScreenName: Chevrolet Silverado\n"
+"   CarScreenNameShort: Chevrolet Silverado\n"
+"   CarClassShortName: Truck\n"
+"   CarClassRelSpeed: 60\n"
+"   CarClassLicenseLevel: 9\n"
+"   CarClassMaxFuelPct: 1.000 %\n"
+"   CarClassWeightPenalty: 0.000 kg\n"
+"   CarClassColor: 0xffffff\n"
+"   IRating: 2419\n"
+"   LicLevel: 19\n"
+"   LicSubLevel: 359\n"
+"   LicString: A 3.59\n"
+"   LicColor: 0x0153db\n"
+"   IsSpectator: 1\n"
+"   CarDesignStr: 2,7a3b01,7a3b01,7a3b01,000000\n"
+"   HelmetDesignStr: 67,270000,55040d,000000\n"
+"   SuitDesignStr: 14,ffffff,aa1d37,6d6e71\n"
+"   CarNumberDesignStr: 0,4,ffffff,030202,6d6e71\n"
+"   CarSponsor_1: 107\n"
+"   CarSponsor_2: 1\n"
+"   ClubName: Georgia\n"
+"   DivisionName: Division 1\n"
+"   CurDriverIncidentCount: 0\n"
+"   TeamIncidentCount: 0\n"
+"\n"
+"SplitTimeInfo:\n"
+" Sectors:\n"
+" - SectorNum: 0\n"
+"   SectorStartPct: 0.000000\n"
+" - SectorNum: 1\n"
+"   SectorStartPct: 0.500000\n"
+"\n"
+"CarSetup:\n"
+" UpdateCount: 1\n"
+" Tires:\n"
+"  LeftFront:\n"
+"   ColdPressure: 210 kPa\n"
+"   LastHotPressure: 210 kPa\n"
+"   LastTempsOMI: 40C, 40C, 40C\n"
+"   TreadRemaining: 100%, 100%, 100%\n"
+"  LeftRear:\n"
+"   ColdPressure: 210 kPa\n"
+"   LastHotPressure: 210 kPa\n"
+"   LastTempsOMI: 40C, 40C, 40C\n"
+"   TreadRemaining: 100%, 100%, 100%\n"
+"  RightFront:\n"
+"   ColdPressure: 338 kPa\n"
+"   LastHotPressure: 338 kPa\n"
+"   LastTempsIMO: 40C, 40C, 40C\n"
+"   TreadRemaining: 100%, 100%, 100%\n"
+"  RightRear:\n"
+"   ColdPressure: 338 kPa\n"
+"   LastHotPressure: 338 kPa\n"
+"   LastTempsIMO: 40C, 40C, 40C\n"
+"   TreadRemaining: 100%, 100%, 100%\n"
+" Chassis:\n"
+"  Front:\n"
+"   BallastForward: 89 mm\n"
+"   NoseWeight: 51.9%\n"
+"   CrossWeight: 52.4%\n"
+"   SteeringRatio: 12:1\n"
+"   SteeringOffset: +4 deg\n"
+"   FrontBrakeBias: 62.5%\n"
+"   TapeConfiguration: Race\n"
+"  LeftFront:\n"
+"   CornerWeight: 4273 N\n"
+"   RideHeight: 149 mm\n"
+"   ShockDeflection: 109 mm 203 mm\n"
+"   SpringDeflection: 87 mm 149 mm\n"
+"   SpringPerchOffset: -125 mm\n"
+"   SpringRate: 70 N/mm\n"
+"   BumpStiffness: +32 clicks\n"
+"   ReboundStiffness: +0 clicks\n"
+"   Camber: +6.0 deg\n"
+"   Caster: +8.6 deg\n"
+"   ToeIn: -3 mm\n"
+"  LeftRear:\n"
+"   CornerWeight: 4368 N\n"
+"   RideHeight: 189 mm\n"
+"   ShockDeflection: 140 mm 254 mm\n"
+"   SpringDeflection: 76 mm 276 mm\n"
+"   SpringPerchOffset: -124 mm\n"
+"   SpringRate: 61 N/mm\n"
+"   BumpStiffness: +20 clicks\n"
+"   ReboundStiffness: +0 clicks\n"
+"   LeftRearToeIn: +7 mm\n"
+"   Camber: +1.3 deg\n"
+"   TrackBarHeight: +273 mm\n"
+"   TruckArmMount: bottom\n"
+"  FrontArb:\n"
+"   Diameter: 51 mm\n"
+"   ArmAsymmetry: Min\n"
+"   ChainOrSolidLink: Solid link\n"
+"   LinkSlack: -0 mm\n"
+"   Preload: -49.4 Nm\n"
+"   Attach: 1\n"
+"  RightFront:\n"
+"   CornerWeight: 4040 N\n"
+"   RideHeight: 171 mm\n"
+"   ShockDeflection: 61 mm 203 mm\n"
+"   SpringDeflection: 80 mm 150 mm\n"
+"   SpringPerchOffset: -147 mm\n"
+"   SpringRate: 67 N/mm\n"
+"   BumpStiffness: +0 clicks\n"
+"   ReboundStiffness: +32 clicks\n"
+"   Camber: -2.4 deg\n"
+"   Caster: +4.5 deg\n"
+"   ToeIn: -3 mm\n"
+"  RightRear:\n"
+"   CornerWeight: 3351 N\n"
+"   RideHeight: 212 mm\n"
+"   ShockDeflection: 134 mm 254 mm\n"
+"   SpringDeflection: 16 mm 153 mm\n"
+"   SpringPerchOffset: -145 mm\n"
+"   SpringRate: 162 N/mm\n"
+"   BumpStiffness: +0 clicks\n"
+"   ReboundStiffness: +32 clicks\n"
+"   RightRearToeIn: -7 mm\n"
+"   Camber: -1.2 deg\n"
+"   TrackBarHeight: +273 mm\n"
+"   TruckArmMount: bottom\n"
+"   TruckArmPreload: -23.2 Nm\n"
+"  Rear:\n"
+"   RearEndRatio: 4.50\n"
+"   ArbDiameter: None\n"
+"   ArmAsymmetry: None\n"
+"   SliderOrSolidLink: Solid link\n"
+"   Preload: -0.0 Nm\n"
+"   LinkSlack: -1 mm\n"
+"\n"
+"...\n"
                ).getBytes());
        System.out.println(m.toString());
        System.out.println(genson.serialize(m));
    }
}
